name: 💡 GSSoC '25 Contribution
description: Share your idea, issue, or proposal for GSSoC 2025!
title: "[GSSoC25] <title>"
# labels: ["gssoc", "good first issue"]

body:
  - type: markdown
    attributes:
      value: |
        # 🌟 GSSoC '25 Contribution Form

        Hey there! 👋  
        We're thrilled to have you as part of **GirlScript Summer of Code 2025**.  
        Please fill out this form so we can understand your idea or issue clearly.

        > ✨ _Let’s make this project better together!_

  - type: input
    id: summary
    attributes:
      label: 📝 Title / Summary
      description: What are you proposing or reporting?
      placeholder: e.g., Add MIT License to the repository
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: 🔍 What's the idea or issue?
      description: Tell us clearly what you're proposing or reporting.
      placeholder: |
        - What's currently happening?
        - What change or feature are you suggesting?
        - Why is it important?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: ⚙️ How will you solve it?
      description: Share your plan, steps, or implementation approach.
      placeholder: |
        1. Fork the repository
        2. Make the necessary changes
        3. Push and create a Pull Request
    validations:
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: ✅ GSSoC '25 Checklist
      options:
        - label: I have searched and confirmed this issue is not already open.
          required: true
        - label: I am a registered participant of GSSoC 2025.
          required: true
        - label: I have starred the repository [Star_here](https://github.com/DhruvJohri/Netflix-Clone)
          required: true
        - label: I agree to follow the project's [Code of Conduct](https://github.com/DhruvJohri/Netflix-Clone/blob/main/CODE_OF_CONDUCT.md).
          required: true
        - label: I follow [@DhruvJohri_ on X](https://x.com/DhruvJohri_) for updates and announcements.
          required: true

  - type: markdown
    attributes:
      value: |
        ---

        ## 🚀 Next Steps

        - ⏳ Wait for a maintainer to assign the issue to you  
        - ✅ Start working once assigned  
        - 💬 Ask questions anytime — we’re here to help!

        > 🙌 **Thank you for contributing to Open Source with GSSoC '25!**
